[package]
name = "molint"
version = "0.1.0"
edition = "2021"

[dependencies]
boys = "0.1.0"
itertools = "0.13.0"
nalgebra = "0.33.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
